site_key: "stitcher"
name: "Stitcher.io"
base_url: "https://stitcher.io"
articles_url: "https://stitcher.io/"
rate_limit: 500

selectors:
  article_links: "nav > a[href*='/blog/']"
  title: "h1"
  content: "article, .wrapper article, main article"
  excerpt: "meta[name='description']"
  author: ".author-name, .post-author, meta[name='author']"
  author_avatar: ".author-avatar img, .author img"
  published_at: "time[datetime], .post-date"
  reading_time: ".reading-time, .read-time"
  tags: ".tags a, .post-tags a, .tag-list a"
  categories: ".category a, .categories a"
  featured_image: "meta[property='og:image']"

browser:
  timeout: 30000
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  wait_until_network_idle: true
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.5"

retry:
  max_attempts: 3
  delay_ms: 1000